newsportal_hw/news/urls.py
from django.urls import path
from .views import (
   PostsList, ItemDetail, PostSearch, PostCreate, PostUpdate, PostDelete, CategoryPostList, subscribe
)


urlpatterns = [
   path('', PostsList.as_view(), name='posts_list'),
   path('<int:pk>', ItemDetail.as_view(), name='item_detail'),
   path('search/', PostSearch.as_view(), name='post_search'),
   path('create/', PostCreate.as_view(), name='news_create'),
   path('articles/create/', PostCreate.as_view(), name='articles_create'),
   path('<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
   path('articles/<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('articles/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('category/<int:pk>', CategoryPostList.as_view(), name='category_list'),
   path('category/<int:pk>/subscribe', subscribe, name='subscribe'),
   path('create/limit', PostCreate.as_view(), name='news_limit'),
   path('articles/create/limit', PostCreate.as_view(), name='articles_limit'),

]

newsportal_hw/newsportal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
]

newsportal_hw/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author (models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    rating = models.IntegerField(default=0)

    def update_rating(self):
        rating_of_posts = Post.objects.filter(author=self).aggregate(rp=Sum('rating'))['rp']
        rating_of_comm = Comment.objects.filter(user_comm=self.user).aggregate(rc=Sum('rating'))['rc']
        rating_of_comm_to_post = Comment.objects.filter(post_comm__author=self).aggregate(rcp=Sum('rating'))['rcp']

        self.rating = rating_of_posts * 3 + rating_of_comm + rating_of_comm_to_post
        self.save()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    category = models.CharField(max_length=64, unique=True)
    subscribes = models.ManyToManyField(User, blank=True, related_name='categories')

    def __str__(self):
        return self.category


class Post(models.Model):
    article = 'AR'
    news = 'NE'

    CHOICE = [
        (article, 'Статья'),
        (news, 'Новость')
    ]

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, through='PostCategory')

    type_post = models.CharField(max_length=2, choices=CHOICE, default=news)
    date_post = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        preview_text = self.text[0:124] + '...'
        return preview_text

    def __str__(self):
        return f'{self.title}: {self.preview()}'

    def get_absolute_url(self):
        return reverse('item_detail', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post_comm = models.ForeignKey(Post, on_delete=models.CASCADE)
    user_comm = models.ForeignKey(User, on_delete=models.CASCADE)

    content = models.TextField()
    date_comm = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()



newsportal_hw/news/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'author',
            'categories',
            'title',
            'text',
        ]

newsportal_hw/news/views.py
import datetime

from django.contrib.auth.mixins import (
    LoginRequiredMixin, PermissionRequiredMixin
)
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView,
)
from .models import Post, Category
from .filters import PostFilter
from .forms import PostForm


class PostsList(ListView):
    model = Post
    ordering = '-date_post'
    template_name = 'news.html'
    context_object_name = 'news'
    paginate_by = 3


class ItemDetail(DetailView):
    model = Post
    template_name = 'item.html'
    context_object_name = 'item'


class PostSearch(ListView):
    model = Post
    template_name = 'search.html'
    context_object_name = 'search'
    ordering = '-date_post'
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['filterset'] = self.filterset
        return context


class PostCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_post',)
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        today = datetime.date.today()
        count_posts = Post.objects.filter(author=post.author, date_post__date=today).count()

        if self.request.path == '/news/articles/create/':
            post.type_post = 'AR'

        if count_posts > 3:
            return render(self.request, 'limit_posts.html', {'author': post.author})

        post.save()
        return super().form_valid(form)


class PostUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ('news.change_post',)
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'
    context_object_name = 'edit'


class PostDelete(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('posts_list')
    context_object_name = 'delete'


class CategoryPostList(PostsList):
    model = Post
    template_name = 'category_post_list.html'
    context_object_name = 'category_posts_list'

    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Post.objects.filter(categories=self.category).order_by('-date_post')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscriber'] = self.request.user not in self.category.subscribes.all()
        context['category'] = self.category
        return context


@login_required
def subscribe(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)
    category.subscribes.add(user)

    massage = 'Вы подписались на рассылку категории'
    return render(request, 'subscribe.html', {'category': category, 'massage': massage})



newsportal_hw/templates/category_post_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
    {% if is_not_subscriber %}
        <button> <a href= "{% url 'subscribe' category.id %}"> Подписаться </a></button>
    {% endif %}
    <h1>Все новости в категории {{category}}</h1>
    <hr>
        <table>
            <tr>
                <td><b>Автор</b></td>
                <td><b>Категория</b></td>
                <td><b>Заголовок</b></td>
                <td><b>Дата публикации</b></td>
                <td><b>Публикация</b></td>
                <td><b>Тип публикации</b></td>
            </tr>
            {% for post in category_posts_list %}
            <tr>
                <td>{{ post.author }}</td>
                <td>{% for categories in post.categories.all %}
                    <a href="{%  url 'category_list' categories.id %}" >{{ categories }}</a>
                    <!--{{ post.categories }}-->
                {% endfor %}</td>
                <td>{{ post.title|censor }}</td>
                <td>{{ post.date_post|date:'d M Y' }}</td>
                <td>{{ post.text|truncatewords:20|censor }}</td>
                <td>{{ post.get_type_post_display }}</td>
            </tr>
            {% endfor %}
        </table>

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

newsportal_hw/templates/item.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
News
{% endblock title %}

{% block content %}
    <h1>{{ item.title|censor }}</h1>
    <h5>{{ item.date_post|date:'d M Y' }}</h5>
    <hr>
    <p>{{ item.text|censor }}</p>
{% endblock content %}

newsportal_hw/templates/limit_posts.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1>{{author}}! К сожалению, больше 3 новостей в сутки публиковать нельзя</h1>
    <h3>Попробуйте завтра!</h3>
    <p>Сейчас вы можете вернуться на главную страницу</p>
    <button><a href="/news/"> Все новости </a></button>
{% endblock content %}

newsportal_hw/templates/main.html
{% extends 'flatpages/default.html' %}

<html>
    <head>
        <title> NewsPortal SignUp/SignIn app </title>
    </head>
    <body>
        <div>
            <h1><a href="/">NewsPortal SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

newsportal_hw/templates/new_post_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Уведомление</title>
</head>
<body>
    {% load account %}
    <h3>Здравствуйте! В вашей любимой категории новая<a href="{{ link }}"> публикация </a></h3>
    <p>{{ text }}</p>
</body>
</html>

newsportal_hw/templates/news.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
    <h1>Все новости</h1>
    <h5>Количество всех новостей: {{news|length}}</h5>
    <hr>
        <table>
            <tr>
                <td><b>Автор</b></td>
                <td><b>Заголовок</b></td>
                <td><b>Дата публикации</b></td>
                <td><b>Публикация</b></td>
                <td><b>Тип публикации</b></td>
            </tr>
            {% for post in news %}
            <tr>
                <td>{{ post.author }}</td>
                <td>{{ post.title|censor }}</td>
                <td>{{ post.date_post|date:'d M Y' }}</td>
                <td>{{ post.text|truncatewords:20|censor }}</td>
                <td>{{ post.get_type_post_display }}</td>
            </tr>
            {% endfor %}
        </table>

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

newsportal_hw/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление публикации</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удалить "{{object.title}}"?</p>
    <input type="submit" value="Delete">
</form>
{% endblock content %}

newsportal_hw/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создание/изменение публикации</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>
{% endblock content %}


newsportal_hw/templates/search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Search
{% endblock title %}

{% block content %}
    <h1>Поиск новости/статьи</h1>
    <hr>
    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>
    <hr>

    {% if search %}
        <table>
            <tr>
                <td><b>Автор</b></td>
                <td><b>Заголовок</b></td>
                <td><b>Дата публикации</b></td>
                <td><b>Публикация</b></td>
                <td><b>Тип публикации</b></td>
            </tr>
            {% for post in search %}
                <tr>
                    <td>{{ post.author }}</td>
                    <td>{{ post.title|censor }}</td>
                    <td>{{ post.date_post|date:'d M Y' }}</td>
                    <td>{{ post.text|truncatewords:20|censor }}</td>
                    <td>{{ post.get_type_post_display }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h3>Новостей нет!</h3>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

newsportal_hw/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h2>{{ massage }} {{ category }}</h2>
    <p>Вы можете вернуться на главную страницу</p>
    <button><a href="/news/"> Все новости </a></button>
{% endblock %}

newsportal_hw/templates/weekly_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h3>Здравствуйте! А вот и новые посты за прошедшую неделю!</h3>
    <ul>
        {% for post in posts %}
            <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>